# Generated by Django 5.2.7 on 2025-11-15 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='brand',
            name='created',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False),
        ),
        migrations.AddField(
            model_name='cctvmodel',
            name='created',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False),
        ),
    ]
