# Generated by Django 5.2.7 on 2025-11-15 17:36

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_rename_created_at_camera_created_brand_created_and_more'), ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id',
                 models.UUIDField(
                     default=uuid.uuid4,
                     editable=False,
                     primary_key=True,
                     serialize=False)),
                ('active',
                 models.BooleanField(
                     default=True)),
                ('created',
                 models.DateTimeField(
                     default=django.utils.timezone.now,
                     editable=False)),
            ],
        ),
    ]
