# Generated by Django 5.2.7 on 2025-10-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_cctv_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCTV',
            new_name='Camera',
        ),
    ]
