# Generated by Django 5.2.7 on 2025-10-23 10:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_rename_cctv_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camera',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cctvmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
