# Generated by Django 5.2.7 on 2025-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_alter_camera_id_alter_camera_identifier_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(
                fields=(
                    'identifier',
                    'model'),
                name='unique_camera_per_model'),
        ),
    ]
