# Generated by Django 5.2.7 on 2025-11-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlight",
            name="status",
            field=models.CharField(default="unknown", max_length=20),
        ),
    ]
